# -*- coding: utf-8 -*-
"""Untitled25.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1HGb8kdv5LLn32J610QDUl3ABU4AV1ToD
"""

from sklearn import datasets

cancer = datasets.load_breast_cancer()

cancer

cancer.data.shape

print(cancer.data[:5])

print(cancer.target)

X = cancer.data
y = cancer.target

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.3, random_state = 109)

from sklearn import svm
classifier = svm.SVC(kernel = 'linear')
classifier.fit(X_train, y_train)
y_pred = classifier.predict(X_test)

from sklearn import metrics

print("Accuracy:", metrics.accuracy_score(y_test, y_pred))

print("Precision:",metrics.precision_score(y_test, y_pred))

print("Recall:",metrics.recall_score(y_test, y_pred))

parameters = [{'kernel': ['poly', 'rbf', 'sigmoid', 'linear']}]

from sklearn.model_selection import RepeatedStratifiedKFold, GridSearchCV

cv = RepeatedStratifiedKFold(n_splits=5, n_repeats=3, random_state=0)
grid_search= GridSearchCV(estimator = classifier, param_grid = parameters, scoring = 'recall', cv = cv, n_jobs = -1)
grid_search = grid_search.fit(X, y)
best_accuracy = grid_search.best_score_
best_parameters = grid_search.best_params_
print("SVM (best score) : ", best_accuracy)
print("best parameter : ", best_parameters)